/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Dominio.Jugador;
import control.Control;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo 5
 */
public class FrmIngresarNombre extends javax.swing.JFrame {

    private static FrmIngresarNombre instance;

    /**
     *
     * @return
     */
    public static FrmIngresarNombre getInstance() {
        if (instance == null) {
            instance = new FrmIngresarNombre();
        }
        return instance;
    }

    /**
     * Creates new form FrmIngresaNombre
     */
    private FrmIngresarNombre() {
        initComponents();
        Random random = new Random();
        cmbColor.setSelectedIndex(random.nextInt((10 - 0) + 1) + 0);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPantalla = new javax.swing.JPanel();
        cmbColor = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fondoAceptar = new javax.swing.JPanel();
        fondoCancelar = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbColor.setBackground(new java.awt.Color(204, 204, 204));
        cmbColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Naranja", "Amarillo", "Verde lima", "Verde", "Turquesa", "Celeste", "Azul", "Morado", "Rosa", "Rosa claro" }));
        panelPantalla.add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 230, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelPantalla.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 230, -1));

        btnAceptar.setBackground(new java.awt.Color(3, 152, 158));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panelPantalla.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 130, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 87, 87));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelPantalla.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, 40));

        fondoAceptar.setBackground(new java.awt.Color(3, 152, 158));
        panelPantalla.add(fondoAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 130, 40));

        fondoCancelar.setBackground(new java.awt.Color(255, 87, 87));
        panelPantalla.add(fondoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IngresarNombre.png"))); // NOI18N
        panelPantalla.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (validar()) {
            Control control = Control.getInstance();
            Jugador jugador = control.crearJugador(txtNombre.getText(), (String) cmbColor.getSelectedItem());

            FrmMenuPrincipal menuJuego = FrmMenuPrincipal.getInstance();
            menuJuego.setJugador(jugador);
            menuJuego.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     *
     * @return
     */
    public boolean validar() {
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor de ingresar nombre", "No válido", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNombre.getText().length() > 15) {
            JOptionPane.showMessageDialog(this, "El nombre es demasiado largo (limitar a 15 caracteres)", "No válido", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoAceptar;
    private javax.swing.JPanel fondoCancelar;
    private javax.swing.JPanel panelPantalla;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
