/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Dominio.Jugador;

/**
 *
 * @author Equipo 5
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private Jugador jugador;

    private static FrmMenuPrincipal instance;

    /**
     *
     * @return
     */
    public static FrmMenuPrincipal getInstance() {
        if (instance == null) {
            instance = new FrmMenuPrincipal();
        }
        return instance;
    }

    /**
     * Creates new form FrmMenuJuego
     */
    private FrmMenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     *
     * @return
     */
    public Jugador getJugador() {
        return jugador;
    }

    /**
     *
     * @param jugador
     */
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPantalla = new javax.swing.JPanel();
        btnCrearPartida = new javax.swing.JButton();
        fondoCrearPartida = new javax.swing.JPanel();
        btnIngresarPartida = new javax.swing.JButton();
        fondoIngresarPartida = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        fondoSalir = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearPartida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrearPartida.setText("Crear Partida");
        btnCrearPartida.setContentAreaFilled(false);
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        panelPantalla.add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, 40));

        fondoCrearPartida.setBackground(new java.awt.Color(255, 189, 89));
        panelPantalla.add(fondoCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, 40));

        btnIngresarPartida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresarPartida.setText("Ingresar a Partida");
        btnIngresarPartida.setContentAreaFilled(false);
        btnIngresarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPartidaActionPerformed(evt);
            }
        });
        panelPantalla.add(btnIngresarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 150, 40));

        fondoIngresarPartida.setBackground(new java.awt.Color(255, 145, 77));
        panelPantalla.add(fondoIngresarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 130, 40));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelPantalla.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, 40));

        fondoSalir.setBackground(new java.awt.Color(255, 87, 87));
        panelPantalla.add(fondoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuJuego.png"))); // NOI18N
        panelPantalla.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        FrmCrearPartida partida = FrmCrearPartida.getInstance();
        partida.setVisible(true);
        partida.setLocationRelativeTo(this);

        this.dispose();
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void btnIngresarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPartidaActionPerformed
        FrmIngresarPartida partida = FrmIngresarPartida.getInstance();
        partida.setVisible(true);
        partida.setLocationRelativeTo(this);

        this.dispose();
    }//GEN-LAST:event_btnIngresarPartidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnIngresarPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoCrearPartida;
    private javax.swing.JPanel fondoIngresarPartida;
    private javax.swing.JPanel fondoSalir;
    private javax.swing.JPanel panelPantalla;
    // End of variables declaration//GEN-END:variables
}
