/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Dominio.Juego;
import Dominio.Jugador;
import Dominio.Tablero;
import control.Control;
import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import socket.Cliente;

/**
 *
 * @author Equipo 5
 */
public class FrmSalaEspera extends javax.swing.JFrame {
    
    private Juego partida;
    private JPanel[] paneles;
    private JLabel[] nombres;
    
    private static FrmSalaEspera instance;

    /**
     *
     * @return
     */
    public static FrmSalaEspera getInstance() {
        if (instance == null) {
            instance = new FrmSalaEspera();
        }
        return instance;
    }

    /**
     * Creates new form FrmSalaDeEspera
     */
    private FrmSalaEspera() {
        this.nombres = new JLabel[4];
        this.paneles = new JPanel[4];
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        Jugador jugador = FrmMenuPrincipal.getInstance().getJugador();
        this.partida = new Juego(new Tablero("10x10"));
        this.partida.setJugador(0, jugador);
        Control control = Control.getInstance();
        setLocationRelativeTo(null);
        fondoJugador1.setBackground(new Color(jugador.getColor()[0], jugador.getColor()[1], jugador.getColor()[2]));
        nombreJugador1.setText(jugador.getNombre());
        paneles[0] = fondoJugador1;
        paneles[1] = fondoJugador2;
        paneles[2] = fondoJugador3;
        paneles[3] = fondoJugador4;
        nombres[0] = nombreJugador1;
        nombres[1] = nombreJugador2;
        nombres[2] = nombreJugador3;
        nombres[3] = nombreJugador4;
        if (jugador.getNombre().equalsIgnoreCase(partida.getJugadores().get(0).getNombre())) {
            this.btnIngresar.setVisible(true);
        } else {
            this.btnIngresar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPantalla = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        fondoJugador1 = new javax.swing.JPanel();
        nombreJugador1 = new javax.swing.JLabel();
        fondoJugador2 = new javax.swing.JPanel();
        nombreJugador2 = new javax.swing.JLabel();
        fondoJugador3 = new javax.swing.JPanel();
        nombreJugador3 = new javax.swing.JLabel();
        fondoJugador4 = new javax.swing.JPanel();
        nombreJugador4 = new javax.swing.JLabel();
        fondoCancelar = new javax.swing.JPanel();
        fondoIngresar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelPantalla.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 130, 40));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        panelPantalla.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 130, 40));

        nombreJugador1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador1.setText("Esperando jugador...");
        nombreJugador1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout fondoJugador1Layout = new javax.swing.GroupLayout(fondoJugador1);
        fondoJugador1.setLayout(fondoJugador1Layout);
        fondoJugador1Layout.setHorizontalGroup(
            fondoJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador1Layout.setVerticalGroup(
            fondoJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoJugador1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(nombreJugador1)
                .addGap(45, 45, 45))
        );

        panelPantalla.add(fondoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 260, 110));

        nombreJugador2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador2.setText("Esperando jugador...");

        javax.swing.GroupLayout fondoJugador2Layout = new javax.swing.GroupLayout(fondoJugador2);
        fondoJugador2.setLayout(fondoJugador2Layout);
        fondoJugador2Layout.setHorizontalGroup(
            fondoJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador2Layout.setVerticalGroup(
            fondoJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(nombreJugador2)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelPantalla.add(fondoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        nombreJugador3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador3.setText("Esperando jugador...");
        nombreJugador3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout fondoJugador3Layout = new javax.swing.GroupLayout(fondoJugador3);
        fondoJugador3.setLayout(fondoJugador3Layout);
        fondoJugador3Layout.setHorizontalGroup(
            fondoJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador3Layout.setVerticalGroup(
            fondoJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoJugador3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(nombreJugador3)
                .addGap(45, 45, 45))
        );

        panelPantalla.add(fondoJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        nombreJugador4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador4.setText("Esperando jugador...");

        javax.swing.GroupLayout fondoJugador4Layout = new javax.swing.GroupLayout(fondoJugador4);
        fondoJugador4.setLayout(fondoJugador4Layout);
        fondoJugador4Layout.setHorizontalGroup(
            fondoJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador4Layout.setVerticalGroup(
            fondoJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoJugador4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(nombreJugador4)
                .addGap(46, 46, 46))
        );

        panelPantalla.add(fondoJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        fondoCancelar.setBackground(new java.awt.Color(255, 87, 87));
        panelPantalla.add(fondoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 130, 40));

        fondoIngresar.setBackground(new java.awt.Color(3, 152, 158));
        panelPantalla.add(fondoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SalaDeEspera.png"))); // NOI18N
        panelPantalla.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("jLabel2");
        panelPantalla.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        FrmMenuPrincipal partida = FrmMenuPrincipal.getInstance();
        partida.setVisible(true);
        partida.setLocationRelativeTo(this);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        Cliente.getInstance().inicia();
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     *
     */
    public void inicia() {
//        FrmTablero partida = new FrmTablero();
//        partida.agregarCantJugadores();
//        this.dispose();
//        FrmTablero partida =  this.partida);
//        partida.setVisible(true);
//        partida.setLocationRelativeTo(this);
    }

    /**
     *
     * @param jugadores
     */
    public void conectar(List<Jugador> jugadores) {
        List<Jugador> tempJugadores = partida.getJugadores();
        for (int i = 0; i < tempJugadores.size(); i++) {
            Jugador next = tempJugadores.get(i);
            
            paneles[i].setBackground(new Color(next.getColor()[0], next.getColor()[1], next.getColor()[2]));
            nombres[i].setText(next.getNombre());
            paneles[i].repaint();
            tempJugadores.set(i, next);
            System.out.println("aeaeaeae " + next);
        }
        
        partida.setJugadores(tempJugadores);
        int contador = 0;
        for (int i = 0; i < tempJugadores.size(); i++) {
            contador++;
        }
        
    }

    /**
     *
     */
    public void mostrarJugadores() {
        fondoJugador1.setBackground(new Color(partida.getJugadores().get(0).getColor()[0], partida.getJugadores().get(0).getColor()[1], partida.getJugadores().get(0).getColor()[2]));
        nombreJugador1.setText(partida.getJugadores().get(0).getNombre());
        
        fondoJugador2.setBackground(new Color(partida.getJugadores().get(1).getColor()[0], partida.getJugadores().get(1).getColor()[1], partida.getJugadores().get(1).getColor()[2]));
        nombreJugador2.setText(partida.getJugadores().get(1).getNombre());
        
        fondoJugador3.setBackground(new Color(partida.getJugadores().get(2).getColor()[0], partida.getJugadores().get(2).getColor()[1], partida.getJugadores().get(2).getColor()[2]));
        nombreJugador3.setText(partida.getJugadores().get(2).getNombre());
        
        fondoJugador4.setBackground(new Color(partida.getJugadores().get(3).getColor()[0], partida.getJugadores().get(3).getColor()[1], partida.getJugadores().get(3).getColor()[2]));
        nombreJugador4.setText(partida.getJugadores().get(3).getNombre());
    }

    /**
     *
     * @return
     */
    public Juego getPartida() {
        return partida;
    }

    /**
     *
     * @param partida
     */
    public void setPartida(Juego partida) {
        this.partida = partida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel fondoCancelar;
    private javax.swing.JPanel fondoIngresar;
    private javax.swing.JPanel fondoJugador1;
    private javax.swing.JPanel fondoJugador2;
    private javax.swing.JPanel fondoJugador3;
    private javax.swing.JPanel fondoJugador4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel nombreJugador1;
    private static javax.swing.JLabel nombreJugador2;
    private static javax.swing.JLabel nombreJugador3;
    private static javax.swing.JLabel nombreJugador4;
    private javax.swing.JPanel panelPantalla;
    // End of variables declaration//GEN-END:variables
}
