
package presentacion;

import juegotimbiriche.Jugador;

/**
 *
 * @author Equipo 5
 */
public class MenuJuego extends javax.swing.JDialog {
    private juegoTimbiriche juego;
    private Jugador jugador;
    private boolean salir;
    
    public MenuJuego(java.awt.Frame parent, boolean modal, juegoTimbiriche juego, Jugador jugador) {
        super(parent, modal);
        this.juego= juego;
        this.jugador=jugador;
        this.salir=true;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearPartida = new javax.swing.JButton();
        fondoCrearPartida = new javax.swing.JPanel();
        btnIngresarPartida = new javax.swing.JButton();
        fondoIngresarPartida = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        fondoSalir = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearPartida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrearPartida.setText("Crear Partida");
        btnCrearPartida.setContentAreaFilled(false);
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, 40));

        fondoCrearPartida.setBackground(new java.awt.Color(255, 189, 89));
        getContentPane().add(fondoCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, 40));

        btnIngresarPartida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresarPartida.setText("Ingresar a Partida");
        btnIngresarPartida.setContentAreaFilled(false);
        btnIngresarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 150, 40));

        fondoIngresarPartida.setBackground(new java.awt.Color(255, 145, 77));
        getContentPane().add(fondoIngresarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 130, 40));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, 40));

        fondoSalir.setBackground(new java.awt.Color(255, 87, 87));
        getContentPane().add(fondoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuJuego.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu2.setText("Ayuda");
        menu.add(jMenu2);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton cancelar que regresa a el menu inicial.
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        this.juego.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    //Boton ingresar partida
    private void btnIngresarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPartidaActionPerformed
        salir=false;
        this.dispose();
        IngresarPartida partida = new IngresarPartida((java.awt.Frame) this.getParent(), true, this.juego, this.jugador);
        partida.setVisible(true);
        partida.setLocationRelativeTo(this);

    }//GEN-LAST:event_btnIngresarPartidaActionPerformed

    //Boton crear partida
    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        salir=false;
        this.dispose();
        CrearPartida partida = new CrearPartida((java.awt.Frame) this.getParent(), true, this.juego, this.jugador);
        partida.setVisible(true);
        partida.setLocationRelativeTo(this);

    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        if(salir)
            this.juego.dispose();
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnIngresarPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoCrearPartida;
    private javax.swing.JPanel fondoIngresarPartida;
    private javax.swing.JPanel fondoSalir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
