
package presentacion;

import java.awt.Color;
import javax.swing.SwingConstants;
import juegotimbiriche.Jugador;

/**
 *
 * @author Equipo 5
 */
public class SalaDeEspera extends javax.swing.JDialog {
    private juegoTimbiriche juego;
    private Jugador jugador;
    
    public SalaDeEspera(java.awt.Frame parent, boolean modal, juegoTimbiriche juego, Jugador jugador) {
        super(parent, modal);
        this.juego= juego;
        this.jugador=jugador;
        initComponents();
        setLocationRelativeTo(null);
        fondoJugador1.setBackground(new Color(jugador.getColor()[0], jugador.getColor()[1], jugador.getColor()[2]));
        nombreJugador1.setText(jugador.getNombre());
        nombreJugador1.setHorizontalAlignment(SwingConstants.CENTER);
        nombreJugador1.setVerticalAlignment(SwingConstants.CENTER);
        nombreJugador2.setHorizontalAlignment(SwingConstants.CENTER);
        nombreJugador2.setVerticalAlignment(SwingConstants.CENTER);
        nombreJugador3.setHorizontalAlignment(SwingConstants.CENTER);
        nombreJugador3.setVerticalAlignment(SwingConstants.CENTER);
        nombreJugador4.setHorizontalAlignment(SwingConstants.CENTER);
        nombreJugador4.setVerticalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        fondoJugador1 = new javax.swing.JPanel();
        nombreJugador1 = new javax.swing.JLabel();
        fondoJugador2 = new javax.swing.JPanel();
        nombreJugador2 = new javax.swing.JLabel();
        fondoJugador3 = new javax.swing.JPanel();
        nombreJugador3 = new javax.swing.JLabel();
        fondoJugador4 = new javax.swing.JPanel();
        nombreJugador4 = new javax.swing.JLabel();
        fondoCancelar = new javax.swing.JPanel();
        fondoIngresar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 130, 40));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 130, 40));

        nombreJugador1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador1.setText("Esperando jugador...");
        nombreJugador1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout fondoJugador1Layout = new javax.swing.GroupLayout(fondoJugador1);
        fondoJugador1.setLayout(fondoJugador1Layout);
        fondoJugador1Layout.setHorizontalGroup(
            fondoJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador1Layout.setVerticalGroup(
            fondoJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoJugador1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(nombreJugador1)
                .addGap(45, 45, 45))
        );

        getContentPane().add(fondoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 260, 110));

        nombreJugador2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador2.setText("Esperando jugador...");

        javax.swing.GroupLayout fondoJugador2Layout = new javax.swing.GroupLayout(fondoJugador2);
        fondoJugador2.setLayout(fondoJugador2Layout);
        fondoJugador2Layout.setHorizontalGroup(
            fondoJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador2Layout.setVerticalGroup(
            fondoJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(nombreJugador2)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(fondoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        nombreJugador3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador3.setText("Esperando jugador...");
        nombreJugador3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout fondoJugador3Layout = new javax.swing.GroupLayout(fondoJugador3);
        fondoJugador3.setLayout(fondoJugador3Layout);
        fondoJugador3Layout.setHorizontalGroup(
            fondoJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador3Layout.setVerticalGroup(
            fondoJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoJugador3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(nombreJugador3)
                .addGap(45, 45, 45))
        );

        getContentPane().add(fondoJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        nombreJugador4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreJugador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador4.setText("Esperando jugador...");

        javax.swing.GroupLayout fondoJugador4Layout = new javax.swing.GroupLayout(fondoJugador4);
        fondoJugador4.setLayout(fondoJugador4Layout);
        fondoJugador4Layout.setHorizontalGroup(
            fondoJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoJugador4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoJugador4Layout.setVerticalGroup(
            fondoJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoJugador4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(nombreJugador4)
                .addGap(46, 46, 46))
        );

        getContentPane().add(fondoJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        fondoCancelar.setBackground(new java.awt.Color(255, 87, 87));
        getContentPane().add(fondoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 130, 40));

        fondoIngresar.setBackground(new java.awt.Color(3, 152, 158));
        getContentPane().add(fondoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SalaDeEspera.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu2.setText("Ayuda");
        menu.add(jMenu2);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        presentacion.Tablero partida = new Tablero((java.awt.Frame) this.getParent(), true, this.juego, this.jugador);
        this.dispose();
        partida.setVisible(true);
        partida.setLocationRelativeTo(this);

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        MenuJuego partida = new MenuJuego((java.awt.Frame) this.getParent(), true, this.juego, this.jugador);
        this.dispose();
        partida.setVisible(true);
        partida.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel fondoCancelar;
    private javax.swing.JPanel fondoIngresar;
    private javax.swing.JPanel fondoJugador1;
    private javax.swing.JPanel fondoJugador2;
    private javax.swing.JPanel fondoJugador3;
    private javax.swing.JPanel fondoJugador4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    // End of variables declaration//GEN-END:variables
}
